name: Hello World
author: Akshay Dhiman
description: Hello World Action
inputs:
  who-to-greet:
    description: "Who to greet?"
    default: Akshay
    required: true
outputs:
  time:
    description: "The Greeting time"
runs:
  using: node12
  main: "dist/index.js"
