on: push

jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/issue
        id: issue
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Issue Title
          body: Issue Body from Custom Actions
          assignees: |
            AkshayCloudAnalogy
            cloudanalogy-testing
      - run: |
          echo ${{ steps.issue.outputs.issue }}
      - uses: ./.github/actions/hello
        id: hello
        with:
          who-to-greet: "World"
      - run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
          echo $HELLO
      - uses: ./.github/actions/hello-docker
        id: hello-docker
        with:
          who-to-greet: "Docker"
      - run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
          echo $HELLO
      - name: Send a Slack Message
        uses: ./github/actions/slack-message-php
        with:
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          message: Hello Slack
